name: Deploy to Local Web Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull origin master

      - name: Update local web server
        run: |
          pwd
          git pull